/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaffa_test;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique Oliveira
 */
public class Kaffa_Test_1_2 extends javax.swing.JFrame {

    /**
     * Creates new form Kaffa_Test_1_2
     */
    public Kaffa_Test_1_2() {
        initComponents();
        this.clear_confirm();
    }
    
    public void clear_confirm(){
        Format_val.setText("");
        Digit_val.setText("");
        Format_val.hide();
        Digit_val.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CNPJ_Field = new javax.swing.JTextField();
        Button_Confirm = new javax.swing.JButton();
        Button_Clear = new javax.swing.JButton();
        Button_Exit = new javax.swing.JButton();
        Format_val = new javax.swing.JLabel();
        Digit_val = new javax.swing.JLabel();

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Confirmar");

        jLabel3.setText("jLabel2");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLEASE ENTER A BRAZILIAN CNPJ");

        CNPJ_Field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CNPJ_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Button_Confirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Confirm.setText("Confirm");
        Button_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfirmActionPerformed(evt);
            }
        });

        Button_Clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Clear.setText("Clear Field");
        Button_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ClearActionPerformed(evt);
            }
        });

        Button_Exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Exit.setText("Exit");
        Button_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExitActionPerformed(evt);
            }
        });

        Format_val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Format_val.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Digit_val.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Digit_val.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(CNPJ_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Format_val, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(Digit_val, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Button_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Button_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Button_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CNPJ_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Format_val, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Digit_val, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ClearActionPerformed
        
        CNPJ_Field.setText("");
        CNPJ_Field.grabFocus();
        this.clear_confirm();
        
    }//GEN-LAST:event_Button_ClearActionPerformed

    private void Button_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfirmActionPerformed
        
        CNPJ_Format_Validation cnpjF = new CNPJ_Format_Validation(CNPJ_Field.getText());
        
        if(cnpjF.checkFormat()){
            Format_val.setText("");
            Format_val.setBackground(Color.GREEN);
            Format_val.setText("Correct CNPJ Format.");
            Format_val.show();
            
            CNPJ_Digits_Validation cnpjD = new CNPJ_Digits_Validation(CNPJ_Field.getText());
            
            if(cnpjD.checkDigits()){
                Digit_val.setText("");
                Digit_val.setBackground(Color.GREEN);
                Digit_val.setText("Correct CNPJ Number.");
                Digit_val.show();
            }
            else{
                Digit_val.setText("");
                Digit_val.setBackground(Color.RED);
                Digit_val.setText("Invalid CNPJ Number.");
                Digit_val.show();
            }
            
        }
        else{
            Format_val.setText("");
            Format_val.setBackground(Color.RED);
            Format_val.setText("Invalid CNPJ Format.");
            Format_val.show();
            Digit_val.setText("");
            Digit_val.setBackground(Color.RED);
            Digit_val.setText("Invalid CNPJ Number.");
            Digit_val.show();
            JOptionPane.showMessageDialog(null, "Invalid CNPJ Format\n\n\nPlease type as: XX . XXX . XXX / XXXX - XX"
                    + "\n\nOr only numbers, without dots, dashes nor slashes.\n\n");
        }
        
        CNPJ_Field.grabFocus();
        
    }//GEN-LAST:event_Button_ConfirmActionPerformed

    private void Button_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExitActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_Button_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kaffa_Test_1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kaffa_Test_1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kaffa_Test_1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kaffa_Test_1_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kaffa_Test_1_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Clear;
    private javax.swing.JButton Button_Confirm;
    private javax.swing.JButton Button_Exit;
    private javax.swing.JTextField CNPJ_Field;
    private javax.swing.JLabel Digit_val;
    private javax.swing.JLabel Format_val;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
